### ISSUE TITLE
False positive on VirusTotal?

### ISSUE THREAD

**Issue by ImjuzCY** [joaomgcd/JoinDesktop#11]
I put the latest release onto VirusTotal to scan and it came back with one detection. Devs might wanna have a look at it. https://www.virustotal.com/gui/file/ad1b21f36b351d9c38eda2edf48bf7e2d0bb6053fecd105adef92606179666a4/detection

**Comment by joaomgcd** [comment]
Sorry, maybe it's because the app allows you to run command line commands? Unfortunately I can't do anything about false positive antivirus scans :(
