### ISSUE TITLE
Windows download link broken

### ISSUE THREAD

**Issue by darkzbaron** [joaomgcd/JoinDesktop#12]
Hi, it seems like the .exe link in the release section is broken so I can't download the latest update. Thanks!

**Comment by joaomgcd** [comment]
Hi. Can you clarify where you're seing the broken link exactly? Thanks!

**Comment by darkzbaron** [comment]
If I go to (https://github.com/joaomgcd/JoinDesktop/releases)

and try to download Join.Desktop.Setup.0.5.0.exe

It goes to the following (http://join.desktop.setup.0.5.0.exe/) link

**Comment by joaomgcd** [comment]
That's strange. For me it shows the correct link: https://github.com/joaomgcd/JoinDesktop/releases/download/v0.5.0/Join.Desktop.Setup.0.5.0.exe

Not sure how you're getting a different one... Can you download from this link?

**Comment by darkzbaron** [comment]
Yes, I can. I just tried with Firefox and it works. Probably some issue with my Chrome installation. I'll investigate and post a follow up. Thanks so much for the push!
