### ISSUE TITLE
TOO MANY REGISTRATION

### ISSUE THREAD

**Issue by darkzbaron** [joaomgcd/JoinDesktop#13]
Hi, I am getting this error when trying to register another device.

**Comment by joaomgcd** [comment]
Hi. Can you please show me a screenshot of that? Thanks in advance.

**Comment by darkzbaron** [comment]
Sorry for the delay. Here you go!
![Screenshot_20201117-173201](https://user-images.githubusercontent.com/5180791/99418250-1ccc8580-28fb-11eb-84d3-79fcf72fdf83.png)

**Comment by joaomgcd** [comment]
Apparently there's a limit for 100 apps that use push messaging on a device at any time: https://groups.google.com/g/android-c2dm/c/P17lZnCoJU0

Did you maybe reach that limit?

**Comment by darkzbaron** [comment]
HI there, I have done some testing.

I uninstalled all apps and changed the device ID.

I forgot to mention that I am running Join on an emulator. It has no issue with Pushbullet but runs into this error with Join, it was working last time around.

Any idea how to circumvent this ?
