### ISSUE TITLE
Clipboard encrypted

### ISSUE THREAD

**Issue by novakin** [joaomgcd/JoinDesktop#15]
Hi 

Im sending 2FA code from my phone to join-desktop. The join action sets the clipboard to the %code variable. 

Issue is that Join displays a proper notification i.e
Setting clipboard
189585

but the clipboard on windows is encrypted.

**Comment by joaomgcd** [comment]
Hi. Can you give me an example of what the clipboard ends up with in that situation? Thanks

**Comment by novakin** [comment]
Something like that

eFb5y+kXYwp9myzeTWz+Og===:=O/sMzc4ST5z5ocAjBHEN0g==

**Comment by novakin** [comment]
Found out that it happens only on local network

**Comment by joaomgcd** [comment]
Thank you! Fixed on the latest code release! :)
