### ISSUE TITLE
Unexpected Error: Timed out

### ISSUE THREAD

**Issue by orrburgel** [joaomgcd/JoinDesktop#19]
Just installed the latest version of Join Desktop and I'm facing a blank screen that says Unexpected Error: Timed out
at the top near the Report button that takes me to a blank page on google when I click it
![image](https://user-images.githubusercontent.com/41600149/101113619-72d24600-35e8-11eb-8398-1f720332f8a8.png)
![image](https://user-images.githubusercontent.com/41600149/101113635-7b2a8100-35e8-11eb-8454-071adc874651.png)

**Comment by joaomgcd** [comment]
Thanks for the report. What OS are you on?

**Comment by orrburgel** [comment]
Windows

**Comment by tommyent** [comment]
Same on Mac Catalina

**Comment by Androz2091** [comment]
Same on Big Sur (Apple Silicon) #17

**Comment by tommyent** [comment]
@joaomgcd when I posted my previous comment I was just checking on the status of of the app.  The console error was a ERR_CONNECTION_REFUSED on 192.168.1.194:41??? (My Pixel) then a Failed to fetch then the caught unexpected error Timed out. 

This is just from memory but I'll try and make some time to run the desktop app again. Would there be any issues switching back and forth from the Chrome extension to the desktop app?

**Comment by deostroll** [comment]
Hello @joaomgcd 

For the sake of knowledge and when you get time please outline the authentication flow.

When I launched this app for the first time, the app just opens up my default browser to complete the google oauth. On successful google login, the browser is redirected to a page. There were some messages saying that I must allow Google Chrome to display notifications. But the main app is blank.

![join_app](https://user-images.githubusercontent.com/415336/110895800-5731b680-8320-11eb-83a1-400330015883.PNG)

**Comment by orrburgel** [comment]
unsubscribe me please

**Comment by rp1231** [comment]
@orrburgel 
I see you closed this.
Did you manage to solve the issue?
If so, would like to know how.
Thanks

**Comment by orrburgel** [comment]
No, This app doesn't work, I closed it because I'm getting tons of notifications
