### ISSUE TITLE
Setup Issues

### ISSUE THREAD

**Issue by the4realpsych** [joaomgcd/JoinDesktop#20]
I followed the setup in the screenshot below - but, I am getting a blank Join page with a circle that turns on the top right corner; not sure how to setup the Desktop app.

![image](https://user-images.githubusercontent.com/76070767/102275401-b3d92d00-3efb-11eb-8f4d-d086b419e8eb.png) - followed the instructions...

![image](https://user-images.githubusercontent.com/76070767/102275456-cb181a80-3efb-11eb-8167-5c3bc76375ea.png) - the result...

Please, I would enjoy any advice you could provide for me; thank you.

**Comment by fenchai23** [comment]
any news on fixing this issue?

**Comment by rp1231** [comment]
Facing the same issue as well.

**Comment by joaomgcd** [comment]
Hi. Very sorry for the super late reply. Is that screenshot on the website or in the desktop app itself?

**Comment by rp1231** [comment]
I'm pretty sure that it is a screenshot of the desktop app itself as I have been facing the same issue.
My desktop app looks the same but has a white background instead of the grey background.

**Comment by joaomgcd** [comment]
Thanks. Can you please try right-clicking the app and see if the console shows any errors?

**Comment by rp1231** [comment]
I just installed the latest version that you released on github.

1)I installed the desktop app.

2)The app opened and opened a browser window.

3)I got a message asking me if I wanted to register my browser as a device.
I clicked yes.

4)Got this error on the browser window: (Even in the previous release I was able to connect sometimes and sometimes not)
![brave_bddgmZKsCk](https://user-images.githubusercontent.com/47380919/115543272-ce168380-a2be-11eb-8f55-f12a1485c60a.png)

5)Screenshot of the console with the error:
![Join_Desktop_1STQ6wTpJt](https://user-images.githubusercontent.com/47380919/115543695-4b41f880-a2bf-11eb-815e-acd17d06be40.jpg)

**Comment by joaomgcd** [comment]
Thank you! Just one more info, can you please do right-click > inspect on the web page (not the app itself) and then check the console there to see what error it's showing in the log? Thanks again!

**Comment by rp1231** [comment]
Here you go!

![brave_RaXKPFj0HR](https://user-images.githubusercontent.com/47380919/115553193-c066fb00-a2ca-11eb-9e21-61a178d5f183.png)

**Comment by joaomgcd** [comment]
Thank you! Seems like your browser is blocking connections to localhost! Do you maybe use adblock or something similar that would do this?

**Comment by rp1231** [comment]
Ahh yes!
I am using brave browser which blocks certain things by default.
It's working now after I disabled the shields for the site.
Thanks

**Comment by joaomgcd** [comment]
Great! :) I've added the message about adblockers for the next release! Thanks!
