### ISSUE TITLE
Issue: Windows 10 UWP app no longer receives messages

### ISSUE THREAD

**Issue by profucius** [joaomgcd/JoinDesktop#21]
Hi there. I posted this on the JoinApp subreddit, but then realized I should post this on your github as a ticket for faster resolution.

I have about 8 different devices on my Join account. All of the have been working fine, up until about a week ago one of them has stopped receiving messages. It will send messages out to other devices with no issue, but when any devices send it messages, nothing happens.

I've tried sending as Note to Self, where it's supposed to show in the notification area, as well as any other method. I also use the AutoRemote/EventGhost integration, and that has stopped working as well. All of my triggerable macros no longer trigger, it is causing me a lot of headache.

I've tried uninstalling the Windows 10 UWP app and reinstalling it. I've signed out and signed in again. I get the list of devices fine. All other devices send and receive just fine, a mixture of Android devices and 2 other Windows 10 UWP apps work fine. But this one machine only will not receive anything.

Anything I can try to fix this issue?

**Comment by joaomgcd** [comment]
Hi. Unfortunately I don't control if pushes are actually delivered to the machine, that part is up to the Microsoft push services. Did you maybe disable something related to that on that specific machine?

**Comment by profucius** [comment]
Oh I see, so it is something on the Windows side? I did disable some feature using a privacy tool, I wonder if that is what did it. I had no idea that would affect Join pushes, since I still get certain other notifications, but I hadn't considered it being push related. I'll try reversing my changes and see if that fixes it.
