### ISSUE TITLE
Options for run on startup and start minimized 

### ISSUE THREAD

**Issue by rp1231** [joaomgcd/JoinDesktop#22]
Hi Jao,
Wanted to add a feature request to add options to run on startup and start minimized.
These would be really helpful features.

Am currently able to get it to run on startup but an option on right clicking the tray icon would really be conveinient.
No diy solution for getting it to start minimized though......

Thanks

**Comment by rp1231** [comment]
Any solution for this?

**Comment by joaomgcd** [comment]
Hi. I can add this in the future, but not right now, thanks :)

**Comment by rp1231** [comment]
Ok thanks

**Comment by gpion** [comment]
As a workaround I've put a shortcut to "Join Desktop.exe" in the startup folder and set "run" as minimized in shortcut properties.
Unfortunately it stills starts with it's window opened.
Could this be considered as a bug ?

**Comment by joaomgcd** [comment]
I've now added an option to auto-launch the app :) Hope it helps!

**Comment by gpion** [comment]
Thanks, It work but I expected it started minimized in tray.

**Comment by joaomgcd** [comment]
Can you please try this version? :) https://drive.google.com/open?id=1wWAi8fxnMsFObo6HZUuvDsteeth1c9qh
I've added an option for that.

**Comment by gpion** [comment]
> Can you please try this version? :)
> https://drive.google.com/open?id=1wWAi8fxnMsFObo6HZUuvDsteeth1c9qh
> I've added an option for that.
>
>
> Waow it was quick!
done, worked flawlessly

--
Gilles

**Comment by joaomgcd** [comment]
Great! :)
