### ISSUE TITLE
Clipboard Sync: "Phone -> PC" not working

### ISSUE THREAD

**Issue by rodrigoswz** [joaomgcd/JoinDesktop#24]
Clipboard Sync from my PC to phone works perfectly, but the reverse (phone to pc) is unfortunately not working.
It only results in a single message in the console log:
`Socket message GCMAutoClipboard`

![image](https://user-images.githubusercontent.com/14058427/116754596-5e4f7980-a9df-11eb-8b17-bd3961a90f5e.png)

Both devices are connected on the same network.

Detail is that if I use the action "Get Clipboard", I can get the clipboard from my phone on my pc normally.

**Join Desktop:** 0.5.2
**Join Android:** 2.4.4-beta
**Device:** Xiaomi Mi 9T
**Android version:** 11 (AOSP, not MIUI)

**Comment by joaomgcd** [comment]
Did you enable syncing from the phone to the PC in the phone app?

**Comment by rodrigoswz** [comment]
Yes

![Screenshot_20210503-103831.png](https://user-images.githubusercontent.com/14058427/116883267-ca0e2e00-abfb-11eb-832b-17e12377c16d.png)

**Comment by rodrigoswz** [comment]
Exactly, I did a test right now to see if the message repeated when copying over and over again
![image](https://user-images.githubusercontent.com/14058427/117450174-444df380-af17-11eb-9e31-c54b2bbe5c7e.png)

**Comment by joaomgcd** [comment]
Does it work if you send the clipboard manually?

**Comment by rodrigoswz** [comment]
I tried send clipboard from phone to pc using bubbles and it worked perfectly, it just doesn't work automatically

**Comment by joaomgcd** [comment]
Hi again. Sorry for the delay. Is it still not working on version 1.0.2?

**Comment by joaomgcd** [comment]
Hhmm, are you using encryption?

If you are, can you please try this version? https://drive.google.com/open?id=1wWAi8fxnMsFObo6HZUuvDsteeth1c9qh

**Comment by rodrigoswz** [comment]
> 
> 
> Hhmm, are you using encryption?

Yes

> If you are, can you please try this version? https://drive.google.com/open?id=1wWAi8fxnMsFObo6HZUuvDsteeth1c9qh

I tested it, it still didn't work

**Comment by joaomgcd** [comment]
Ok, I think I cracked it this time! 😁

**Comment by rodrigoswz** [comment]
> 
> 
> Can you please try this version? https://drive.google.com/open?id=1wWAi8fxnMsFObo6HZUuvDsteeth1c9qh

YES! Working correctly with this version!

Thank you so much João, closing this issue :)

**Comment by joaomgcd** [comment]
Great! :) Glad it works!!
