### ISSUE TITLE
Clipboard Sync PC-PC not working

### ISSUE THREAD

**Issue by Orevin** [joaomgcd/JoinDesktop#25]
Hi there,

As the title states, clipboard sync PC-PC not working, using 0.5.2. The desktops show up as registered, but not under settings for clipboard sync. Sync between desktop and phone works well.

![Home - 0205](https://user-images.githubusercontent.com/32856801/120069536-0c385d00-c04c-11eb-882b-8ffd6a023472.png)
![Home - 0206](https://user-images.githubusercontent.com/32856801/120069537-0cd0f380-c04c-11eb-8031-752d43cc2b04.png)

**Comment by joaomgcd** [comment]
Ah yes, that is not supported yet, sorry!
