### ISSUE TITLE
Connection error while setting up the app for the first time 

### ISSUE THREAD

**Issue by Zed0004** [joaomgcd/JoinDesktop#26]
I get this error after clicking on the login option when the app first opens. 
I have installed the chrome extension.
And the mobile device is also on the same wifi network.

![120216604-db774400-c254-11eb-93f4-3b70f7af3cba](https://user-images.githubusercontent.com/84900576/120221818-acfd6700-c25c-11eb-9ae5-1425f7d08d4a.png)

**Comment by joaomgcd** [comment]
Are you maybe blocking connections to localhost on that browser?

**Comment by Zed0004** [comment]
It was an issue with brave browser [https://github.com/brave/brave-browser/issues/15107](url)

**Comment by joaomgcd** [comment]
Thanks for confirming!
