### ISSUE TITLE
Does the Join Desktop App follow the system proxy settings?

### ISSUE THREAD

**Issue by mmqmzk** [joaomgcd/JoinDesktop#30]
OS: Windows 10 21H1, browser: Chrome 91, Join Desktop App 1.0.0 windows version.

I live in China, so I'm using a http proxy to access Google.

When I opened Join Desktop App, it opened a web page `https://joinjoaomgcd.appspot.com/?settings`, the page said the companion app was ok, then open `http://127.0.0.1:9876/?code=xxxxxxxxx` to authorize, after a few seconds, the new page revealed the following message:

```json
{"message":"request to https://oauth2.googleapis.com/token failed, reason: connect ETIMEDOUT 172.217.24.10:443","type":"system","errno":"ETIMEDOUT","code":"ETIMEDOUT"}
``` 

And there's a message on the Chrome Dev Tools console:
```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

I can use Join Chrome extension and Join new webapp behind the proxy without any problem.

Usually, I get connection reset or timeout when accessing Google's web page or API directly.

As the title, I guess the desktop app doesn't follow system proxy setting.

**Comment by joaomgcd** [comment]
Hi. Where exactly are you setting up that proxy? Thanks!

**Comment by mmqmzk** [comment]
Settings -> Network & Internet -> Proxy

**Comment by joaomgcd** [comment]
Ok, I tried something. Could you please check if this version works? https://drive.google.com/open?id=1wWAi8fxnMsFObo6HZUuvDsteeth1c9qh

**Comment by mmqmzk** [comment]
Nice, it works. 👍

**Comment by joaomgcd** [comment]
Nice! :D Glad it works!
