### ISSUE TITLE
Error Loading Join Desktop

### ISSUE THREAD

**Issue by Creeps642** [joaomgcd/JoinDesktop#32]
![image](https://user-images.githubusercontent.com/59230027/123378945-ad53fe00-d58d-11eb-9603-64c5a79f683c.png)

Updated from 0.5 and now i have this message when i open the app. Then it doesn't work

**Comment by joaomgcd** [comment]
Hi. What version are you using now?

**Comment by Creeps642** [comment]
I tried 1.1 and 1.2, it's the same.

25 juin 2021 13:52:11 João Dias ***@***.***>:

**Comment by joaomgcd** [comment]
Can you please uninstall the app (and clear its data) and then reinstall and try again? Thanks!

**Comment by Creeps642** [comment]
I tried this time with BCUninstaller and it worked. I am sorry for the inconvenience. Have a great day Joao

**Comment by joaomgcd** [comment]
Glad to hear that, thanks!
