### ISSUE TITLE
Login does not work

### ISSUE THREAD

**Issue by update-freak** [joaomgcd/JoinDesktop#34]
Hello developers,

I can't login to the program on Windows 10 21H1.
I get the message in the attachment. 

Join version: Join.Desktop.Setup.1.0.2
Windows Version: Windows 10 21H1
![windows](https://user-images.githubusercontent.com/40196995/123516346-e11d4980-d69b-11eb-8673-c024f93c6be9.png)

**Comment by joaomgcd** [comment]
Hi. What happens when you click the button?

**Comment by update-freak** [comment]
Then I get this window:
![1](https://user-images.githubusercontent.com/40196995/124152035-73a25c00-da93-11eb-84be-22ffb29e8e69.png)
After Login I get this window again:
![2](https://user-images.githubusercontent.com/40196995/124152116-86b52c00-da93-11eb-9cfd-6c71ee7f8c5d.png)

**Comment by joaomgcd** [comment]
That means that something on your browser is blocking cookies for the website or from Google and so it can't stay signed in.

**Comment by jice73** [comment]
@update-freak In case you're using it, Privacy Badger was causing me that exact issue.

**Comment by update-freak** [comment]
That's what it was: use Privacy Badger and ublock origin.
I don't get any items in the app as shown in the screenshot:
![pic](https://user-images.githubusercontent.com/40196995/124184600-1c63b200-daba-11eb-9172-fd34a6c6af7c.png)

**Comment by joaomgcd** [comment]
Try uninstalling and re-installing the app now that you've unblocked things. :) Glad that was it!
