### ISSUE TITLE
Please add 'Hide text content' option

### ISSUE THREAD

**Issue by mjoshd** [joaomgcd/JoinDesktop#36]
When using 'Use Native Notifications' in the Join Desktop app, would it be possible to add the option to 'Hide text content in notifications' like there is with the Chrome extension?

![image](https://user-images.githubusercontent.com/35782597/124290079-063d0c80-db21-11eb-84c8-708960c5b152.png)

**Comment by joaomgcd** [comment]
Ok, added for next release. Thanks :)
