### ISSUE TITLE
[Request] Backup/Restore settings

### ISSUE THREAD

**Issue by rodrigoswz** [joaomgcd/JoinDesktop#37]
It would be great if there was an option to backup data in the cloud.
That way I wouldn't lose my Actions and Keyboard Shortcuts if something bad happened.

In addition to being able to use them on another computer without having to configure everything again.

**Comment by tommyent** [comment]
You can do feature requests here as well https://joaoapps.helprace.com/

**Comment by joaomgcd** [comment]
I really don't want to store user settings in the cloud. To get a backup you can simply copy the  `C:\Users\YOUR_USER\AppData\Roaming\Join Desktop` folder :) All the data is there.
