### ISSUE TITLE
[Feature Request] Option to disable 'Automatically open any received links'

### ISSUE THREAD

**Issue by leifalbor** [joaomgcd/JoinDesktop#38]
![image](https://user-images.githubusercontent.com/29937194/124382090-ee27e180-dd08-11eb-973f-e8aa9eb41467.png)

Any chance we could have this option from the Chrome extension retrofitted into the desktop app?

**Comment by joaomgcd** [comment]
Ok, updated and added for next release! :) Thank you!

**Comment by leifalbor** [comment]
Nice, thanks Joao!
