### ISSUE TITLE
[Feature Request] Proper launch minimized and minimize to tray on linux

### ISSUE THREAD

**Issue by kennethso168** [joaomgcd/JoinDesktop#40]
```
System:
  Kernel: 5.8.0-59-generic x86_64 bits: 64 compiler: N/A 
  Desktop: Cinnamon 4.8.6 Distro: Linux Mint 20.1 Ulyssa 
  base: Ubuntu 20.04 focal
```

In my system, Join Desktop does not minimize to tray. It just minimize like a normal window.

Also when Launch Minimized is checked, when I open Join Desktop again it just flashes and the window does not show up (likely it has minimized to nowhere). I have to reinstall to fix this.

I can work around this with the program called [kdocker](http://kdocker.sourceforge.net/)

But it would be nice if we can have proper launch minimized and minimize to tray on linux

Thank you

**Comment by joaomgcd** [comment]
Unfortunately I couldn't find a way to properly minimize to tray on Linux, sorry! I fixed the issue on startup with the minimize on launch option is enabled for the next release. Thanks!
