### ISSUE TITLE
API link issues

### ISSUE THREAD

**Issue by mat4444** [joaomgcd/JoinDesktop#41]
Hi,
It's a great feature to embed the API links creation right in the app, but I have noticed a few issues with the 'Create a Join API link for your device' in the desktop app: 

- The URL always starts with `file:///` instead of `https://joinjoaomgcd.appspot.com/` when doing the same in the Web App. I'm not sure if the URL is supposed to work with `file:///` but it does not in my case.
- There is no copy Button for the generated URL. in the desktop app. A right-click on the URL (to copy it) opens chrome dev panel. Would it be possible to fix this ?
- The fields are not very readable when we are typing text in it. See screenshot below:
![Sans titre](https://user-images.githubusercontent.com/53400792/125161156-053f5700-e181-11eb-814d-582c1f7b8401.png)

It would be great if this could be fixed :) !

**Comment by mat4444** [comment]
I don't know if it's directly related to this issue, but when I am pushing a URL to the desktop app via an API link , this does not work: it either open Windows Explorer or opens a Windows dialog box asking which program should open it (when the port is defined). 
However, it works when I send a URL to the Chrome extension or an Android device. It also work when I am using the share option in any webpage from an Android device to the Desktop app.

**Comment by joaomgcd** [comment]
Fixed the visual issue :) Will be available for the next release.

About the API not working to the Desktop app, can you try sending just with the Text and Title fields and see if that works?

**Comment by mat4444** [comment]
The API works when sending only with the text and title fields. However, when I had a URL in the API link, it opens Windows Explorer (or ask which program to use)
![Sans titre](https://user-images.githubusercontent.com/53400792/125537740-eca92242-9062-413f-9778-fb68c84df0fa.png)

**Comment by joaomgcd** [comment]
Can you give me an example of a URL you're using? Thanks!

**Comment by mat4444** [comment]
I'm trying to open a URL in the form : xxxxx.duckdns.org:8089. It opens a windows pop asking which software should be used to open it.
The same API link sent to the chrome extension works perfectly.

Additionally, basic URL like www.google.com, www.youtube.com etc. simply open the Windows explorer.

**Comment by joaomgcd** [comment]
Does it work if you send with https:// before the URL?

**Comment by mat4444** [comment]
Yes, it does work with http:// or https:// ! Thanks !
But it's a bit inconsistent with the behavior of the chrome extension, that does not require it for the first URL example I gave.

**Comment by joaomgcd** [comment]
The difference is that in Chrome you can't open other kinds of URLs like an app can :) But I guess I can try guessing if the received url is supposed to be an http one...

**Comment by joaomgcd** [comment]
Ok, changed it :) If there's no protocol in the URL it'll automatically add https://

Hope this helps!

**Comment by mat4444** [comment]
Hi João, when do you think this change will be effective ?

**Comment by joaomgcd** [comment]
Not sure. I wanted to add some more significant changes before I pushed this out as an update 😅 What version of the app are you using? I can send you the installer directly...

**Comment by mat4444** [comment]
No worries! I don't know why, but I thought I would be a change on the server side. I can wait, no problem :) !

**Comment by joaomgcd** [comment]
ok, cool!
