### ISSUE TITLE
Clipboard sync issue with mobile data

### ISSUE THREAD

**Issue by Morgane-dotcom** [joaomgcd/JoinDesktop#43]
Hi,
I have noticed an issue with the clipboard sync: I can't send my clipboard FROM my android device TO the desktop app, when they're in different network (basically mobile data for my phone). However, the opposite works (desktop app to android device).
That's annoying since it works with the Chrome extension.
Hope you can have a look at it :)
Thanks !

**Comment by joaomgcd** [comment]
Yes, the desktop app can only sync the clipboard on the same local network for now, sorry!
