### ISSUE TITLE
[Feature Request] - Better notification

### ISSUE THREAD

**Issue by Morgane-dotcom** [joaomgcd/JoinDesktop#44]
Hi again,
I personally like to use the native notification style on Windows 10. That allows me to quickly see if I have received a notification while I was away from my PC. On the contrary, the new notifications disappear without leaving a trace, and they're way too large in my opinion.
The problem with the native notification is that the quick action buttons don't work at all (impossible to reply to a message, pick the numeric code in an automatic message etc.). Is there a plan to improve the native notification behavior ? Thanks !

**Comment by joaomgcd** [comment]
Hi. You can check the missed notifications in the app in the notifications tab :)

About windows notifications, unfortunately I can't add those features. That's actually why I created the non-native ones 😅

**Comment by Morgane-dotcom** [comment]
Ok, I see.
Would it be possible to fix the position the non-native notifications ? They tend to appear way above the Windows task bar.
![Sans titre](https://user-images.githubusercontent.com/85899830/125540830-b46de49f-ef00-4b8f-8737-764462ee98bc.png)

Also, the function to copy a number/code from a SMS now extracts a dot (.) if the number is directly followed by a period at the end of a sentence (i.e "your code is 123456." ==> extracts 123456. instead of 123456). The chrome extension does not extract the dot.
