### ISSUE TITLE
Join API URL structure is incorrect for Clipboard

### ISSUE THREAD

**Issue by richaardvark** [joaomgcd/JoinDesktop#53]
When creating a Join API URL to set a device's clipboard the generated parameter is incorrectly coded and generates "&**url**clipboard=" instead of "&clipboard=" which then results in an error when the URL is loaded.

This typo is of course not in this electron web app itself but is in the general Join Web website and affects all platforms that use the web interface.

**Comment by joaomgcd** [comment]
Thank you! Fixed! :)

**Comment by richaardvark** [comment]
> Thank you! Fixed! :)

Hey João (sorry if I'm not supposed to comment on a closed issue), it does seem to be fixed on the "Join Web" website interface, but I have tried both the .deb and appimage versions of the Linux Join Desktop app and they are still making making the wrong URL string for the clipboard parameter (are still making "&urlclipboard=" instead of "&clipboard=").

**Comment by joaomgcd** [comment]
Yeah, sorry about that, I need to put new builds out for the various versions to fix on those as well, sorry!
