### ISSUE TITLE
Trying to send action from join app on phone to windows client seems to show base64 strings instead of command

### ISSUE THREAD

**Issue by MindCaged** [joaomgcd/JoinDesktop#60]
I don't know if I'm doing something wrong, but I have the windows client installed on windows 7. I'm trying to use Join to run a command in EventGhost. I go into the join app on my phone and setup a custom action.
Command Name: Testing
Command: test234

under Devices I select the windows client, and the Chrome extension, when I click run the Chrome Notification says test234, but the desktop client shows some Base64 strings(or what I think are base64).

wEb7VTpMdQeMUPQ2MF60rg===:=kXe6yvJoS77AbPXNWj9qHg==

I tried using a base64 converter to translate and don't get anything meaningful so I'm not sure if it's encrypted or salted or something.

Checking other things it seems even if I try to send notications or a note it also shows up in the notification as random Base64-like strings.

**Comment by joaomgcd** [comment]
Hi. That means that you set different encryption keys on each device :)

**Comment by MindCaged** [comment]
Thank you, I thought about that but I didn't have one set on the desktop client, and I was 99 percent sure I never set one for the android app, but I checked and there was a password set on the app. I don't know if this was done by default or if I set one and completely forgot. I cleared the password on the app and the notification pops up correctly now. I still can't get it to redirect the pushes to eventghost, but that might be a separate issue. I managed to get autoremote working and it seems to work a bit better with eventghost, so I guess I'll jut go with that.

**Comment by MindCaged** [comment]
Hmm, if I clear passwords on both the app and the client it seems to work, but I set the exact same password on both, and now it's showing base64 again. Are the app and desktop client using different encryption or something?

**Comment by joaomgcd** [comment]
Hhmm, they aren't.. It should work if both of them have the password set. Are your devices communicating via local network or via the internet?

**Comment by MindCaged** [comment]
Local network, but I just tried switching to over the internet and same problem. Also, tried restarting the desktop app, and it gives me an "Couldn't load the app. (Timed out)." message, but it seems to be loaded and seems to be receiving pushes, so I'm not sure what's timing out.
