### ISSUE TITLE
Error Loading Join Desktop Couldn't load the app. (TypeError: Cannot read property 'imageUrl' of null). Please check your connection and try again.

### ISSUE THREAD

**Issue by funkey7dan** [joaomgcd/JoinDesktop#63]
Hello, 
I keep getting this error message when trying to start the desktop app.
I tried restarting the pc and reinstalling the app but to no avail.
On right click the dev panel shows this error:
"Failed to load resource: https://www.googleapis.com/oauth2/v1/userinfo?alt=json the server responded with a status of 401 ()"

**Comment by funkey7dan** [comment]
I'm running a pihole on the network, but i don't see blocked queries when trying to launch join.
Also the firefox and chrome interfaces for join work fine, so I don't think the server is blocked.
that's the request that is denied in the app:
![image](https://user-images.githubusercontent.com/72495653/170184774-a169387d-511d-4815-8fd6-cf86d7713d50.png)
So i feel like maybe the google authorization is not working properly for me?

**Comment by oned0** [comment]
I also get this error. Did you find any solution?

**Comment by funkey7dan** [comment]
I found a post on Reddit that suggested using [BCuninstaller ](https://www.bcuninstaller.com/)to uninstall the app and reinstall it, that fixed the issue for me ( After authenticating again using google)
