### ISSUE TITLE
0.3.1 is missing for Mac

### ISSUE THREAD

**Issue by tommyent** [joaomgcd/JoinDesktop#7]

**Comment by joaomgcd** [comment]
Yeah, I don't have access to my mac right now so I can't build it sorry. I've already fixed the code to not alert the user if the installer file is not available but that fix will only come with 0.3.1 :)

I'll update the mac build when I can, thank you!

**Comment by tommyent** [comment]
I can clone and commit it if you want or send you the dmg.

**Comment by joaomgcd** [comment]
That's OK, thank you :) I'll be on my mac soon enough.
